import { CornerDownRight } from "lucide-react";

/** Suggested next questions, generated by rules from the retrieved sources (no extra AI call). */
export default function FollowUps({ items, onPick }: { items: string[]; onPick: (q: string) => void }) {
  if (!items.length) return null;
  return (
    <ul className="mt-3 flex flex-wrap gap-2" aria-label="Suggested follow-up questions">
      {items.slice(0, 3).map((q, i) => (
        <li key={q} className="animate-rise" style={{ animationDelay: `${i * 80}ms` }}>
          <button
            onClick={() => onPick(q)}
            className="glass flex items-center gap-2 rounded-full px-3.5 py-2 text-left text-xs leading-snug text-uoc-700 transition hover:-translate-y-0.5 hover:!bg-white/70 active:scale-95 dark:text-uoc-100 dark:hover:!bg-white/10"
          >
            <CornerDownRight className="h-3.5 w-3.5 shrink-0 text-magenta-500" />
            {q}
          </button>
        </li>
      ))}
    </ul>
  );
}
