"""Short chat titles: generated by the LLM on a conversation's first message (heuristic fallback offline)."""

from __future__ import annotations

import re

from langchain_core.language_models.chat_models import BaseChatModel

from app.rag.llm import message_text
from app.rag.text import tokenize

MAX_TITLE = 48

TITLE_PROMPT = (
    "Write a short title (2 to 5 words) for a chat that starts with the message below. "
    "It is about the University of Cyberjaya. Use Title Case, no quotes, no trailing punctuation, "
    "and the same language as the message. Output ONLY the title.\n\nMessage: {question}"
)


def heuristic_title(question: str) -> str:
    """Offline fallback: the first few meaningful words, title-cased."""
    words = tokenize(question)[:5]
    title = " ".join(w.capitalize() for w in words) if words else question.strip()
    return clean_title(title) or "New Chat"


def clean_title(raw: str) -> str:
    t = message_text(raw).strip().splitlines()[0] if raw.strip() else ""
    t = re.sub(r"^(title\s*:\s*)", "", t, flags=re.I)
    t = re.sub(r"[\"'`*_#]+", "", t).strip().rstrip(".!?:;,-– ")
    return t[:MAX_TITLE].rstrip()


def plausible(title: str, question: str) -> bool:
    """Reject replies that are not a title (free routed models sometimes answer with a label like "Safety: safe")."""
    words = title.split()
    if not 1 <= len(words) <= 7 or ":" in title:
        return False
    stems = {w[:4] for w in tokenize(question)}
    return any(w[:4] in stems for w in tokenize(title))


async def generate_title(llm: BaseChatModel | None, question: str) -> str:
    """One cheap LLM call; any failure (quota, network, empty answer) falls back to the heuristic."""
    if llm is not None:
        try:
            out = await llm.ainvoke(TITLE_PROMPT.format(question=question[:400]))
            title = clean_title(message_text(out.content))
            if len(title) >= 2 and plausible(title, question):
                return title
        except Exception:  # noqa: BLE001
            pass
    return heuristic_title(question)
