---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	route(route)
	rewrite(rewrite)
	retrieve(retrieve)
	rerank(rerank)
	grade(grade)
	broaden(broaden)
	generate(generate)
	chitchat(chitchat)
	fallback(fallback)
	__end__([<p>__end__</p>]):::last
	__start__ --> route;
	broaden --> retrieve;
	grade -.-> broaden;
	grade -.-> fallback;
	grade -.-> generate;
	rerank --> grade;
	retrieve --> rerank;
	rewrite --> retrieve;
	route -.-> chitchat;
	route -. &nbsp;retrieve&nbsp; .-> rewrite;
	chitchat --> __end__;
	fallback --> __end__;
	generate --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
