/** Site-wide constants; NEXT_PUBLIC_* values are read at build time (see frontend/.env.example). */

export const SITE_URL = "https://cyberjaya.edu.my";
export const UOC_URL = SITE_URL;

export const AUTHOR_NAME = "Maksuda Akhter Tumpa";
export const AUTHOR_URL = process.env.NEXT_PUBLIC_AUTHOR_URL ?? "";

export const OPERATOR_NAME = process.env.NEXT_PUBLIC_OPERATOR_NAME?.trim() || AUTHOR_NAME;

export const APP_URL = (process.env.NEXT_PUBLIC_SITE_URL?.trim() || "http://localhost:3100").replace(/\/+$/, "");

export const CONTACT_EMAIL = process.env.NEXT_PUBLIC_CONTACT_EMAIL?.trim() ?? "";

export const REPO_URL = (process.env.NEXT_PUBLIC_REPO_URL?.trim() ?? "").replace(/\/+$/, "");

export const APP_NAME = "AskUoC";
export const APP_TAGLINE = "Ask anything about the University of Cyberjaya - with sources.";
export const APP_DESCRIPTION =
  "AskUoC is an independent AI assistant that answers questions about the University of Cyberjaya - programmes, fees, scholarships, admission and campus life - using the university's public website, with cited sources.";

export const DISCLAIMER =
  "AskUoC is an independent project. It is not affiliated with, endorsed by or operated by the University of Cyberjaya. Answers are generated by AI from the university's public website and may be incomplete, out of date or wrong - always verify important details (fees, dates, entry requirements) with the university.";

/** ISO date the legal/info pages were last reviewed. */
export const LEGAL_UPDATED = "2026-09-26";

export const INFO_PAGES = [
  { href: "/privacy", label: "Privacy" },
  { href: "/terms", label: "Terms" },
  { href: "/cookies", label: "Cookies" },
  { href: "/accessibility", label: "Accessibility" },
  { href: "/about", label: "About" },
] as const;

export const INDEXABLE_PATHS = [
  "/",
  "/about",
  "/privacy",
  "/terms",
  "/cookies",
  "/accessibility",
  "/security",
] as const;

export const formatDate = (iso: string) =>
  new Date(iso).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" });
